{{/*
IngressClass for Traefik — registers Traefik as an Ingress controller.
*/}}
{{- if .Values.ingressController.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingressController.ingressClassName }}
  labels:
    {{- include "common-lib.labels" (dict "root" . "extraLabels" .Values.labels) | nindent 4 }}
  annotations:
    {{- include "common-lib.annotations" (dict "root" . "extraAnnotations" .Values.annotations) | nindent 4 }}
spec:
  controller: traefik.io/ingress-controller
{{- end }}
