{{- if .Values.security.authorizationPolicy.allowWebhook.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-istiod-webhook
  namespace: {{ .Values.global.istioNamespace | default "istio-system" }}
  labels:
    {{- include "istiod.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: istiod
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - "cluster.local/ns/kube-system/sa/generic-garbage-collector"
        - "cluster.local/ns/kube-system/sa/replicaset-controller"
        - "cluster.local/ns/kube-system/sa/deployment-controller"
    to:
    - operation:
        paths:
        - "/inject"
        - "/validate"
        methods:
        - "POST"
{{- end }}
