{{- if .Values.customAutoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "istiod.fullname" . }}
  namespace: {{ .Values.global.istioNamespace | default "istio-system" }}
  labels:
    {{- include "istiod.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod{{ if .Values.revision }}-{{ .Values.revision }}{{ end }}
  minReplicas: {{ .Values.customAutoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.customAutoscaling.maxReplicas | default 5 }}
  metrics:
  {{- if .Values.customAutoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.customAutoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.customAutoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.customAutoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- with .Values.customAutoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
